✨ [Feature/oauth2.0] 카카오 소셜로그인 구현
depromeet/antoon-api pull request #20
Opened 2022-04-13 12:45 UTC by twoosky

### 💡 개요

* OAuth2.0 로그인 구현
* jwt 토큰 생성 구현
* 토큰 재발급 구현

- resolved #18 

### 📑 작업 사항

![Screenshot from 2022-04-12 17-10-02](https://user-images.githubusercontent.com/50009240/163175327-3c3ca239-60ae-499a-bd79-c81b711e5ad9.png)

1. 아래 url로 프론트에서 로그인 요청함
    * redirect_uri는 인증이 완료된 후, 백엔드 API에 접근할 수 있는 Access Token을 쿼리스트링으로 받을 수 있는 프론트엔드 페이지
```
http://localhost:8080/oauth2/authorization/kakao?redirect_uri=http://localhost:8080/home
```

3. 백엔드에서 카카오에게 리다이렉트함
```
https://kauth.kakao.com/oauth/authorize
?client_id=  
    ${kakao.clientID}  
    &redirect_uri= http://localhost:8080/login/oauth2/code/kakao
    &response_type=code
```
  * 위 url로 요청하면 카카오는 redirect_rui로 authorization code 담아 보냄

4. 백에서는 token 요청 uri에 authorization code를 담아 카카오 서버에 access token 요청
```
https://kauth.kakao.com/oauth/token
```

5. 카카오 서버로부터 받은 access token으로 카카오에 유저 정보 요청
6. 백엔드는 사용자 정보를 받아 저장하고, JWT 생성
7. 정상적으로 로그인 완료되면 1번의 redirect_uri에 access token을 파라미터로 포함하여 프론트로 리다이렉트.
    * `OAuth2SuccessHandler` 에 구현

### ✒️ 코드 리뷰 요청 사항

* 위 로직으로 소셜로그인을 한다면 프론트로부터 인가코드를 받지 않아도 될거 같습니다.

2022-04-13 14:28 UTC, DongGeon0908 requested changes
고생하셨습니다!

조금 더 추상화할 부분이 있는 것 같아요! 그리고 본인만의 스타일로 리펙토링하면 더욱 좋을 것 같네용

2022-04-13 14:28 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/config/SecurityConfig.java
>      }
접근제한자가 없는 이유가 궁금합니다!

2022-04-13 14:28 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/security/oauth2/application/CustomOAuth2UserService.java
>      public OAuth2User loadUser(OAuth2UserRequest oAuth2UserRequest){
oAuth2UserRequest -> reqeust로 써도 됩니당

2022-04-13 14:28 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/security/oauth2/application/CustomOAuth2UserService.java
>      }
역할 분리가 필요할 것 같아요!!

2022-04-13 14:28 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/security/oauth2/handler/OAuth2SuccessHandler.java
> +                .build().toUriString();
어차피 String인데 Uri 만들어서 toString()으로 바꿔주는게 의미가 있는지 궁금합닏!

2022-04-13 14:28 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/security/token/JwtFilter.java
> +    private Authentication getAuthentication(String token) {
필터에서 있을 내용이 아닌 것 같습니다!

2022-04-13 14:28 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/security/token/JwtTokenProvider.java
>  public class JwtTokenProvider {
Builder의 책임을 어디까지 가져갈 것인지 고민해보면 좋을 것 같아요!!

2022-04-13 14:28 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/user/application/AuthService.java
> +                .orElseThrow(Exception::new);
모든 Exception을 다포함하는 에러일까요?

2022-04-13 14:28 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/user/application/AuthService.java
> +    public TokenResponse refresh(String token) throws Exception {
throws Exception 요것은 왜 필요할까요?

2022-04-13 14:28 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/user/application/AuthService.java
> +            throw new Exception();
BusinessException을 만든 이유가 없어질 수 있어용

2022-04-14 09:58 UTC, twoosky commented on src/main/java/kr/co/antoon/config/SecurityConfig.java
>      }
오잉 그러네요 ...? 접근제한자가 없는데 오류가 안났네요
현재 코드에서는 passwordEncoder를 사용하지 않아 삭제한 상태입니다!
감사합니다 :)

2022-04-14 09:59 UTC, twoosky commented on src/main/java/kr/co/antoon/security/oauth2/application/CustomOAuth2UserService.java
>      public OAuth2User loadUser(OAuth2UserRequest oAuth2UserRequest){
오오 감사합니다 ㅎㅎ

2022-04-14 10:02 UTC, twoosky commented on src/main/java/kr/co/antoon/security/oauth2/application/CustomOAuth2UserService.java
>      }
토큰을 생성하는 것과 user를 저장하는 것의 역할분리를 말씀하시는 건가요 :question::exclamation:
리뷰 감삼다 극락님 열쩡

2022-04-14 10:06 UTC, twoosky commented on src/main/java/kr/co/antoon/security/oauth2/handler/OAuth2SuccessHandler.java
> +                .build().toUriString();
UriComponentsBuilder를 사용하면 URI 구조를 좀 더 알아보기 쉽게 작성할 수 있는거 같아 사용했습니다!
따로 특별한 이유는 없습니당 리뷰 감사합니다 :D

2022-04-14 10:08 UTC, twoosky commented on src/main/java/kr/co/antoon/security/token/JwtFilter.java
> +    private Authentication getAuthentication(String token) {
넵 jwtTokenProvider 클래스로 메소드 옮기는게 맞을거 같습니다 !! 감사합니다 :+1:

2022-04-14 10:10 UTC, twoosky commented on src/main/java/kr/co/antoon/user/application/AuthService.java
> +                .orElseThrow(Exception::new);
BusinessException을 사용해 코드 수정하겠습니다 ~!
리뷰 감사합니다 ㅎ-ㅎ

2022-04-14 10:18 UTC, twoosky commented on src/main/java/kr/co/antoon/security/token/JwtTokenProvider.java
>  public class JwtTokenProvider {
Builder의 책임 ... 어렵군 .. 요 좀 더 고민해보고 코드 수정하겠습니다 :no_mouth:
리뷰 감삼다 극락!

2022-04-14 10:19 UTC, twoosky commented on src/main/java/kr/co/antoon/user/application/AuthService.java
> +            throw new Exception();
오마이갓 절대 안되지

2022-04-14 11:30 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/security/oauth2/application/CustomOAuth2UserService.java
>      }
넵넵 맞아요!!

2022-04-14 11:31 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/security/oauth2/handler/OAuth2SuccessHandler.java
> +                .build().toUriString();
Url을 사용하지 않는데, builder를 사용하신게 궁금했어요!
현재 toString으로 변환하는 로직이 있는데, 굳이 builder가 필요해 보이지 않았거든요!

2022-04-14 11:31 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/security/token/JwtFilter.java
> +    private Authentication getAuthentication(String token) {
넹넹~

2022-04-14 11:32 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/user/application/AuthService.java
> +            throw new Exception();
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
항상 확장을 고려하는 설계를 생각해보시길!!

2022-04-14 16:33 UTC, devsungmin requested changes
전체적으로 동건님께서 코드 리뷰를 잘해주셔서 해당 부분 참고해서 리팩터링 하시면 좋을 것 같습니다.

전체적으로 코드에 불필요한 주석이 너무 많은 듯한 느낌이 있습니다.
최대한 코드는 주석 없이 다른 사람이 조금만 본다면 이해 할 수 있도록 구현하는게 가독성에도 좋고 깔끔해 보입니다.

고생하셨습니다.

2022-04-14 16:33 UTC, devsungmin commented on src/main/java/kr/co/antoon/security/oauth2/domain/KakaoOAuth2UserInfo.java
> +        // kakao_account 안에 profile이라는 JSON객체가 있다. (nickname, profile_image_url)
코드 설명에 대한 주석은 최대한 제거하고 commit 하는게 좋아요

2022-04-14 16:33 UTC, devsungmin commented on src/main/java/kr/co/antoon/security/oauth2/handler/OAuth2SuccessHandler.java
> +        log.info(targetUri);
```suggestion
        log.info("targetURi : {}", targetUri);
```

로깅을 할 때는 명확하게 어떤 값인지 알아 볼 수 있도록!

2022-04-14 16:33 UTC, devsungmin commented on src/main/java/kr/co/antoon/security/token/JwtTokenProvider.java
>      private static final long ACCESS_TOKEN_EXPIRE_TIME = 1 * 60 * 1000L;  // 1분
이전에 작업 했던 코드를 주석처리 하기보단 과감하게 제거하는게 좋아요!

2022-04-14 16:33 UTC, devsungmin commented on src/main/java/kr/co/antoon/user/presentation/AuthController.java
> +        return authService.refresh(token);
해당 API가 있을 이유가 혹시 있을까요?

2022-04-14 16:59 UTC, twoosky commented on src/main/java/kr/co/antoon/security/token/JwtTokenProvider.java
>      private static final long ACCESS_TOKEN_EXPIRE_TIME = 1 * 60 * 1000L;  // 1분
과감하게 .. 오케이 입력 .. 
리뷰 감삼다 대장님 :D

2022-04-14 16:59 UTC, twoosky commented on src/main/java/kr/co/antoon/security/oauth2/handler/OAuth2SuccessHandler.java
> +        log.info(targetUri);
넵 !!

2022-04-14 17:03 UTC, twoosky commented on src/main/java/kr/co/antoon/user/presentation/AuthController.java
> +        return authService.refresh(token);
토큰 재발급을 위해 구현한 API인데, 토큰 재발급은 API가 필요없는건가요 ..?!

2022-04-14 17:04 UTC, devsungmin commented on src/main/java/kr/co/antoon/user/presentation/AuthController.java
> +        return authService.refresh(token);
아 프론트에서 호출해서 재발급 받는 용도로 사용하나요?

2022-04-14 17:55 UTC, twoosky commented on src/main/java/kr/co/antoon/security/oauth2/handler/OAuth2SuccessHandler.java
> +                .build().toUriString();
음 이게 답이 될진 모르겠지만 UriComponentsBuilder를 사용하면 직관적이기도 하지만 인코딩을 자동으로 해준다고 해요 ! 
현재 코드에서는 인코딩이 필요하지 않지만 아는게 이 방법 뿐이라 ..
일반적으로 url string을 만들 때 어떤 방식으로 구현하나요 ?
`"http://localhost:8080/home?token=" + accessToken` 이런 식으로 그냥 문자열로 만드나요?

2022-04-14 18:10 UTC, twoosky commented on src/main/java/kr/co/antoon/user/presentation/AuthController.java
> +        return authService.refresh(token);
네 맞아요 !! 대장님 혹시 안주무시면 아니 주무시겠죠? 
PR 올리려는데 이거 PR 닫고 다시 새로 올리면 되나요 ?

2022-04-15 00:05 UTC, devsungmin commented on src/main/java/kr/co/antoon/user/presentation/AuthController.java
> +        return authService.refresh(token);
그냥 해당 PR에 커밋하시면 자동으로 올라옵니다.

2022-04-15 17:37 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/security/oauth2/handler/OAuth2SuccessHandler.java
> +                .build().toUriString();
넵! 상관없습니다! 그리고 저 url은 별도로 숨겨서 사용해요!

2022-04-16 15:39 UTC, merged