✨ [Feature/OAuth2.0] Spring Security를 활용한 kakao 로그인 구현
depromeet/antoon-api pull request #22
Opened 2022-04-14 06:05 UTC by xx10222

### 💡 개요
- kakao oauth login with spring security

- resolved #6

### 📑 작업 사항
- 현재 로그인하면 jwt토큰을 넘겨줍니다
- 회원가입 부분도 추가해서 금방 pr 올리겠습니다

### ✒️ 코드 리뷰 요청 사항

### ✔️ 코드 리뷰 반영 사항
- spring security 적용
- 이전 구현 내용을 아예 엎고 새로 구현했습니다..ㅎㅎ

2022-04-14 11:29 UTC, DongGeon0908 requested changes
고생하셨습니다!!! 짧은 시간에 많은 수정이 있었네영~~ 간단하게 리뷰 남겨요!!

1. 삽입과 수정, 삭제가 일어나는 부분에는 log를 추가하는게 좋아요! (모니터링용!)
2. 상황에 맞는 exception을 만들어보세요!
3. 중복되는 로직들이 몇개 보여요! 비슷한 것들은 재활용 가능한 코드를 만들어보는게 어떨까요?

그리고 마지막으로 궁금한 점이 있는데, 이전 pr을 닫고 새롭게 생성한 이유가 무엇일까용?

2022-04-14 11:29 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/oauth/presentation/OauthController.java
> +        throw new RuntimeException();
상황에 맞는 exception을 재정의하는 건 어떨까요?

2022-04-14 11:29 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/oauth/presentation/OauthController.java
> +            return "HAPPY NEW TOKEN";
테스트용도일까요?

2022-04-14 11:29 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/oauth/presentation/OauthController.java
> +        throw new RuntimeException();
상황에 맞는 exception을 재정의하는 건 어떨까요?

2022-04-14 11:29 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/oauth/handler/OAuth2AuthenticationSuccessHandler.java
> +        log.info("{}", token);
이 로그가 어떤 로그인지 설명도 같이 있으면 좋을 것 같아요!

2022-04-14 11:29 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/oauth/handler/OAuth2AuthenticationSuccessHandler.java
> +//    }
사용하지 않는 코드라면 지우는게 가독성에 좋아요!

2022-04-14 11:29 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/oauth/filter/JwtAuthFilter.java
> +                    .picture("프로필 이미지에요").build();
로컬에서 DB 연동하고 진행하시면 될 것 같아요!
그리고 build를 밑으로!

2022-04-14 11:29 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/oauth/dto/OAuth2Attribute.java
> +                throw new RuntimeException();
상황에 맞는 Exception!!!

2022-04-14 11:29 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/oauth/application/CustomOAuth2UserService.java
> +        log.info("{}", oAuth2Attribute);
해당 log가 무엇인지 설명이 들어가면 좋을 것 같아용!

2022-04-14 11:29 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/oauth/application/TokenService.java
> +                        .compact());
요건 무엇일까용? 설명 부탁드려요!

2022-04-14 11:29 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/oauth/dto/Token.java
> +}
해당 클래스는 dto라는 명칭을 추가하는게 좋을 것 같아요!

2022-04-14 16:23 UTC, devsungmin requested changes
불필요한 코드 제거 및 상황에 맞는 예외 처리 부탁드립니다.

또한 변수 명을 명확하게 알아 볼 수 있도록 리팩터링 하는게 좋을 것 같아요

2022-04-14 16:23 UTC, devsungmin commented on src/main/java/kr/co/antoon/oauth/application/TokenService.java
> +//    @Override
불필요한 주석은 제거해주세요 ㅎㅎ

2022-04-14 16:23 UTC, devsungmin commented on src/main/java/kr/co/antoon/oauth/application/TokenService.java
> +//    @Override
```suggestion

```

2022-04-14 16:23 UTC, devsungmin commented on src/main/java/kr/co/antoon/oauth/application/TokenService.java
> +//    @Override
```suggestion

```

2022-04-14 16:23 UTC, devsungmin commented on src/main/java/kr/co/antoon/oauth/dto/OAuth2Attribute.java
> +                throw new RuntimeException();
이런 경우 Custom Exception을 만들어서 상황에 맞게 필요한 예외 처리를 해야해요
물론 Custom Exception을 만드는 것 보다는 표준 예외처리를 상황에 맞게 사용하는걸 추천합니다.

2022-04-14 16:23 UTC, devsungmin commented on src/main/java/kr/co/antoon/oauth/dto/Token.java
> +public class Token {
```suggestion
public class TokenDTO {
```

동건님 말씀대로 명확한 명칭 dto 패키지에 포함되더라도 실제 코드에서 보면 DTO인지 구분이 안갑니다.

2022-04-14 16:23 UTC, devsungmin commented on src/main/java/kr/co/antoon/oauth/handler/OAuth2AuthenticationSuccessHandler.java
> +//    }
```suggestion

```

2022-04-14 16:23 UTC, devsungmin commented on src/main/java/kr/co/antoon/oauth/handler/OAuth2AuthenticationSuccessHandler.java
> +        // 최초 로그인이라면 회원가입 처리를 한다.
```suggestion
        // TODO: 최초 로그인이라면 회원가입 처리를 한다.
```
이 후에 작업이 필요한 경우에 일반 주석과 구분하기 위해서 TODO 혹은 FIXME 같은 걸 주석으로 달아주면 인텔리제이에서 색상으로 표시되서 나중에 작업 할 곳을 찾기 더 편합니다.

2022-04-14 16:23 UTC, devsungmin commented on src/main/java/kr/co/antoon/oauth/handler/OAuth2AuthenticationSuccessHandler.java
> +        log.info("{}", token);
로깅은 명확하게
```suggestion
        log.info("TOKEN : {}", token);
```

2022-04-14 16:23 UTC, devsungmin commented on src/main/java/kr/co/antoon/oauth/handler/OAuth2AuthenticationSuccessHandler.java
> +        response.addHeader("Refresh", token.getRefreshToken());
```suggestion
        response.addHeader("AccessToken", token.getToken());
        response.addHeader("RefreshToken", token.getRefreshToken());
```

조금 더 명확하게 가는게 좋습니다.

2022-04-14 16:23 UTC, devsungmin commented on src/main/java/kr/co/antoon/oauth/presentation/OauthController.java
> +            return "HAPPY NEW TOKEN";
```suggestion
            return "";
```
불필요한 코드 제거

2022-04-14 18:47 UTC, xx10222 commented
> 

원래 이전 PR에 이어서 올리려고 했는데 어디서 꼬인건지 PR이 계속 안보내져서 새로 보냈습니다😭
친절하고 자세한 코드리뷰 너무 감사드려요ㅠㅠ 하나하나 꼼꼼히 살펴보면서 반영하겠습니다!

2022-04-15 01:19 UTC, zkdlu commented on src/main/java/kr/co/antoon/oauth/presentation/OauthController.java
> +            return "HAPPY NEW TOKEN";
오. "HAPP NEW TOKEN" 보니 아마 구현에 참고한 블로그가 제 블로그 글 같네요.

2022-04-15 01:29 UTC, yunyoung1819 commented on src/main/java/kr/co/antoon/config/SecurityConfig.java
> +                .oauth2Login().loginPage("/token/expired")
극락님과 성민님이 이미 훌륭한 리뷰를 남겨주셔서 리뷰할게 별로 없지만 저도 도움을 드리고싶어 리뷰를 남겨드려용!
.oauth2Login().loginPage("/token/expired")는 테스트를 위해 사용하신거같지만 향후 프론트엔드와 연동되면
빼먹지말고 바뀌어야할 것 같아용!

2022-04-15 01:37 UTC, yunyoung1819 commented on src/main/java/kr/co/antoon/oauth/application/CustomOAuth2UserService.java
> +        log.info("{}", oAuth2Attribute);
log를 작성하실 때 System.out.println("블라블라~ :" + oAuth2Attribute)로 쓰는 것보다 위에 하신 것처럼 log의 치환문자 {} 를 쓰면 문자열 연산이 일어나지 않아 성능 및 가독성 면에서 더 좋습니다. 굳이에용!
log를 작성하는 방법은 팀마다 다 다르긴한데 저같은 경우는 회사에서 로그가 발생한 클래스명 + 메소드명 등을 같이 적어줍니다. 그러면 수많은 로그에서 해당 파일 위치를 보고 바로 검색할 수 있어 좋더라구용!

2022-04-15 01:44 UTC, yunyoung1819 commented on src/main/java/kr/co/antoon/oauth/handler/OAuth2AuthenticationSuccessHandler.java
> +        log.info("{}", token);
테스트를 위한 Info 성 로그는 나중에 시간이 지나면 엄청 쌓이면 힘들기 때문에 테스트 끝나면 지워주는게 좋아용! 디버깅을 위해 필요한 로그라고 생각되시면 log.debug 로 변경해주시는 것두 좋겠네용! ㅎㅎ

2022-04-15 01:47 UTC, yunyoung1819 approved these changes
극락님과 성민님이 이미 훌륭한 리뷰를 달아주셔서 전 리뷰할게 별로 없었네용!
구현하시느라 고생 많으셨어용! 굳굳!

2022-04-15 06:18 UTC, xx10222 commented on src/main/java/kr/co/antoon/oauth/presentation/OauthController.java
> +            return "HAPPY NEW TOKEN";
> 오. "HAPP NEW TOKEN" 보니 아마 구현에 참고한 블로그가 제 블로그 글 같네요.

어머 안녕하세요... 큰 도움 받았습네다...

2022-04-16 06:36 UTC, yunyoung1819 commented on src/main/java/kr/co/antoon/oauth/presentation/OauthController.java
> +            return "HAPPY NEW TOKEN";
ㅋㅋㅋㅋㅋㅋ

2022-04-16 15:39 UTC, merged