✨ [Feature/webtoon-graph-invest-21] 그래프 스냅샷 및 알고리즘 구현
depromeet/antoon-api pull request #25
Opened 2022-04-16 08:11 UTC by DongGeon0908

### 💡 개요

- 그래프 표현을 위한 스코어 기능 구현

- resolved #21 

### 📑 작업 사항

- 그래프 스코어 스냅샷 구현
- 스케쥴링 구조 잡기

추가적으로 알고리즘 기능 구현을 추가할 예정입니다!

### ✒️ 코드 리뷰 요청 사항

- 아직 완성되지는 않았어요!

### ✔️ 코드 리뷰 반영 사항

2022-04-16 08:12 UTC, DongGeon0908 commented
저녁에 다시 집에 와서 마무리 작업 진행할게요! 모두 극락코딩~

2022-04-17 05:44 UTC, DongGeon0908 commented
아직 알고리즘 구현을 진행하지 않았습니다!!
생각보다 오래 걸릴 것 같네요 ㅜㅜ

2022-04-20 13:31 UTC, devsungmin requested changes
리팩터링 시급합니다 극락님 ㅠㅠㅠ

2022-04-20 13:31 UTC, devsungmin commented on src/main/java/kr/co/antoon/graph/TestController.java
> +    }
?????

2022-04-20 13:31 UTC, devsungmin commented on src/main/java/kr/co/antoon/graph/TestController.java
> +}
?????

2022-04-20 13:31 UTC, devsungmin commented on src/main/java/kr/co/antoon/graph/domain/GraphScoreSnapshot.java
> +import javax.persistence.*;
꼭 *이여야 할까요...

2022-04-20 13:31 UTC, devsungmin commented on src/main/java/kr/co/antoon/graph/facade/GraphScoreFacade.java
> +            }
리팩터링이 시급합니다...

2022-04-21 04:04 UTC, yunyoung1819 approved these changes
무언가 도움이 될만한 리뷰를 달고 싶었는데.. 담에 좀 더 공부해서 리뷰 달게여! 고생 많으셨습니다! 안툰 홧팅!

2022-04-21 04:04 UTC, yunyoung1819 commented on src/main/java/kr/co/antoon/graph/domain/GraphScoreSnapshot.java
> +import javax.persistence.*;
저도 인텔리제이의 Auto Import 기능을 쓰고 있는데 저렇게 변환해주더라구여!

2022-04-21 15:04 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/graph/TestController.java
> +    }
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2022-04-21 15:04 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/graph/TestController.java
> +}
살...살려줘~

2022-04-21 15:05 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/batch/webtoon/WebtoonCrawlingBatchScheduler.java
> +        webtoonCrawlingDailyJob.run(Platform.NAVER);
앗! 맞춰서 가겠슴둥!!

2022-04-21 15:06 UTC, DongGeon0908 commented
map으로 처리하도록 로직 수정했슴둥!
controller는 아직 못 지웠네요 ㅋㅋ

2022-04-22 13:33 UTC, DongGeon0908 commented
수정 완료했습니다!
@devsungmin @yunyoung1819

2022-04-22 14:14 UTC, devsungmin requested changes
Go to Papago

2022-04-22 14:14 UTC, devsungmin commented on src/main/java/kr/co/antoon/graph/domain/vo/GraphStatus.java
> +    MAINTATIN("유지"),
```suggestion
    MAINTAIN("유지"),
```

2022-04-22 14:14 UTC, devsungmin commented on src/main/java/kr/co/antoon/graph/domain/GraphScoreSnapshot.java
> +            default -> new GraphScoreSnapshot(graphScore, webtoonId, GraphStatus.MAINTATIN);
```suggestion
            default -> new GraphScoreSnapshot(graphScore, webtoonId, GraphStatus. MAINTAIN);
```

2022-04-22 14:14 UTC, devsungmin commented on src/main/java/kr/co/antoon/graph/domain/vo/GraphStatus.java
> +        return MAINTATIN;
```suggestion
        return MAINTAIN;
```

2022-04-22 14:14 UTC, devsungmin commented on src/main/java/kr/co/antoon/graph/facade/GraphScoreFacade.java
> +                            .orElse(GraphStatus.MAINTATIN);
```suggestion
                            .orElse(GraphStatus. MAINTAIN);
```

2022-04-22 14:15 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/graph/domain/vo/GraphStatus.java
> +    MAINTATIN("유지"),
좋은 것 같습니다!! 감사합니다~!!

2022-04-22 14:15 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/graph/facade/GraphScoreFacade.java
> +                            .orElse(GraphStatus.MAINTATIN);
찾아주셔서 감사합니다!!

2022-04-22 14:15 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/graph/domain/vo/GraphStatus.java
> +        return MAINTATIN;
감사합니다~~~!!!!

2022-04-22 14:19 UTC, devsungmin approved these changes
LGTM 👍

2022-04-22 14:20 UTC, merged