✨[Feature/webtoon-detail] 웹툰 상세페이지 조회 기능 구현
depromeet/antoon-api pull request #29
Opened 2022-04-24 01:53 UTC by xx10222

### 💡 개요
웹툰 상세페이지 조회에 필요한 데이터를 조회하여 리턴한다

- resolved #14

### 📑 작업 사항
- @PathVariable을 통해 webtoon의 id로 상세 페이지를 조회하면 해당 웹툰의 제목, 소개, 작가, url, 썸네일, 장르, 완결 여부, 플랫폼 정보를 DB로부터 조회해서 리턴한다
- 웹툰 상세페이지에 있는 댓글, 좋아요, 탑승/하차, 그래프 데이터 정보는 담고 있지 않습니다..!ㅠ
- 사용자에 따라 달라지는 데이터(좋아요, 탑승/하차 여부)는 로그인 성공 후 고민해보겠습니다..!

### ✒️ 코드 리뷰 요청 사항
- 우선 제가 상세 페이지 조회 시 필요한 데이터만 조회하도록 했는데 이상한 부분이나 수정 또는 추가할 부분이 있다면 말씀해주세요! :)

### ✔️ 코드 리뷰 반영 사항

2022-04-24 01:56 UTC, xx10222 commented
오잉.. 저게 왜저럴까요....하하...

2022-04-24 05:45 UTC, devsungmin commented
rebase를 안하셨군요 ㅠㅠ

2022-04-24 08:21 UTC, xx10222 commented
> rebase를 안하셨군요 ㅠㅠ

앗 저번에 머지하신거 까먹고 고대로 작업했네여... 이제 생각났어요...🤦🏻‍♀️🥺

2022-04-24 15:24 UTC, DongGeon0908 requested changes
흐엉~~ 기존 커밋 내용도 같이 와서 너무 많다능!

2022-04-24 15:24 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/webtoon/presentation/WebtoonController.java
> +                .build();
service에서 controller로 넘어올때 dto를 보내는게 좋아요!
그리고 common에 보면 responsedto가 있을거에요!!
해당 클래스를 살펴보시길!!

2022-04-24 15:24 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/webtoon/presentation/WebtoonController.java
> +        List<String> writer = webtoonWriterService.findNameByWebtoonId(id);
요런것들도 전부 service에서 끝내는게 좋아요! 혹은 facade에서!

2022-04-24 15:24 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/webtoon/presentation/WebtoonController.java
> +@RequestMapping("/webtoon")
/api/v1/webtoons

2022-04-24 15:24 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/webtoon/presentation/WebtoonController.java
> +    @GetMapping("/detail/{id}")
/api/v1/webtoons/{id} 요렇게

2022-04-24 15:24 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/webtoon/dto/WebtoonDetailDto.java
> +}
swagger schema를 사용합시당!

2022-04-24 15:24 UTC, DongGeon0908 commented on src/main/java/kr/co/antoon/webtoon/application/WebtoonWriterService.java
> +    }
한줄로 끝낼 수 있을 것 같아용

2022-04-28 05:05 UTC, yunyoung1819 approved these changes
어느 분이 하게될지 모르지만 웹툰 상세페이지 조회 시 추가 필요한 필드들(댓글 좋아요, 탑승한 개미수, 하차한 개미수 등)도 있어용! 고생 많으셨습니당!

2022-04-30 05:09 UTC, DongGeon0908 commented
가즈아!~

2022-04-30 16:47 UTC, devsungmin requested changes
조회 기능 구현인데 바뀐 파일이 엄청 많고... 이거 merge 하면 큰일날거 같아요.... rebase 쳐서 다시 올려야 할거 같아여

2022-04-30 16:47 UTC, devsungmin commented on gradlew.bat
> +:omega
이 파일 변경점이 뭔가요?

2022-04-30 16:47 UTC, devsungmin commented on src/main/java/kr/co/antoon/error/dto/ErrorMessage.java
> +    EXPIRED_TOKEN("해당 토큰은 만료된 토큰입니다."),
뭔가 구글과 파파고의 만남이 많이 느껴지는건 기분 탓이겠죠...?

2022-05-01 04:37 UTC, merged

2022-05-01 04:50 UTC, DongGeon0908 commented
머지 진행필요 to Staging